management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.banking: DEBUG
    org.springframework.cloud: DEBUG